title: Cristian Martínez
logo: /assets/img/logo.png
description: Industrial engineer and data scientist with practical experience in Classification Modeling, Regression, Clustering, NLP, Transfer Learning, Reinforcement Learning and Computer Vision.
show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
