title: Cristian Martínez
logo: /assets/img/logo.png
description: Industrial Engineer and Data Scientist with hands on Practical Experience in Classification Modeling, Regression, Clustering, NLP, Transfer Learning, Reinforcement Learning and Computer Vision.
show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
